[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "testRepo"
version = "1.0.3rc"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  "src"
]
